import json, subprocess, re, sys

slugs = [
    'arista-ai-data-center-networking-2026',
    'marvell-ai-custom-chips-data-center-2026',
    'broadcom-ai-networking-vmware-dominance-2026',
    'l3harris-defense-avionics-contracts-2026',
    'nvidia-cuda-ai-moat-2026'
]

for s in slugs:
    a = json.load(open(f'articles/posts/{s}.json'))
    
    # Combine all text
    all_text = a.get('title','') + '\n' + a.get('subtitle','') + '\n' + a.get('summary','') + '\n'
    
    # Extract body text without HTML
    body = a['bodyHtml']
    body_text = re.sub(r'<[^>]+>', ' ', body)
    body_text = re.sub(r'&[a-z]+;', ' ', body_text)
    body_text = re.sub(r'&#\d+;', ' ', body_text)
    body_text = re.sub(r'[0-9,.$%]+', ' ', body_text)
    body_text = re.sub(r'[^\w\s\'-]', ' ', body_text)
    all_text += body_text
    
    words = all_text.lower().split()
    words = [w.strip("'") for w in words if len(w.strip("'")) > 2]
    unique = sorted(set(words))
    
    # Run aspell
    r = subprocess.run(['aspell', 'list', '--lang=en_US'], input='\n'.join(unique), capture_output=True, text=True, timeout=10)
    misspelled = [w.strip() for w in r.stdout.strip().split('\n') if w.strip()]
    
    if misspelled:
        # Filter financial/tech jargon that aspell doesn't know
        signal_jargon = {
            'moat', 'moats', 'hyperscaler', 'hyperscalers', 'hyperscaler', 'hyperscalers',
            'drawdown', 'flywheel', 'flywheels', 'compounder', 'compounders',
            'backlog', 'backlogs', 'bullish', 'bearish',
            'monetize', 'monetization', 'monetizing',
            'turnaround', 'turnarounds', 'comeback', 'comebacks',
            'renaissance', 'tailwind', 'tailwinds', 'headwind', 'headwinds',
            'outperform', 'outpacing', 'outpaced', 'outsized',
            'underappreciated', 'underserved', 'undervalued', 'overvalued',
            'reacceleration', 'inflection', 'optionality',
            'chipmaker', 'chipmakers', 'semiconductor', 'semiconductors',
            'datacenter', 'datacenters', 'hyperscale',
            'mispriced', 'underpriced', 'overpriced',
            'trailing', 'subscription', 'subscriptions', 'annualized',
            'non', 'gaap', 'ebitda', 'capex', 'opex',
            'proprietary', 'interconnect', 'modularity',
            'workload', 'workloads', 'bottleneck', 'bottlenecks',
            'virtualization', 'containerization', 'orchestration',
            'microservices', 'scalability', 'resiliency',
            'redundancy', 'optimization', 'optimizing',
            'ecosystem', 'ecosystems', 'platformization',
            'monetization', 'monetizing', 'monetized',
            'generationally', 'accretive', 'dilutive',
            'consolidation', 'consolidated', 'digitization',
            'modernization', 'transformation', 'reorganization',
            'restructuring', 'downsizing', 'rightsizing',
            'divestiture', 'divestitures', 'disintermediation',
            'stickiness', 'incremental', 'decoupling',
            'secular', 'cyclical', 'countercyclical',
            'recessionary', 'inflationary', 'deflationary',
            'disinflation', 'reflation', 'stagflation',
            'policymakers', 'policymaker', 'decisionmakers',
            'shareholder', 'shareholders', 'stakeholder', 'stakeholders',
            'multiyear', 'multibillion', 'multimillion', 'multidecade',
            'workstation', 'workstations', 'motherboard', 'motherboards',
            'supercomputer', 'supercomputers', 'supercomputing',
            'microprocessor', 'microprocessors', 'microcontroller', 'microcontrollers',
            'semicustom', 'semiformal',
            'telecommunications', 'telecom',
            'cybersecurity', 'cyber',
            'electro', 'optical', 'optoelectronics',
            'monolithic', 'heterogeneous', 'homogeneous',
            'photolithography', 'lithography',
            'transistor', 'transistors', 'nanometer', 'nanometre',
            'petaflop', 'petaflops', 'exaflop', 'exaflops',
            'teraflop', 'teraflops', 'gigaflop', 'gigaflops',
            'tflops', 'gflops', 'teraflops',
            'supercluster', 'hyperconverged',
            'hypervisor', 'hypervisors', 'container', 'containers',
            'kubernetes', 'docker', 'openshift',
            'cryptocurrency', 'cryptocurrencies',
            'blockchain', 'stablecoin', 'stablecoins',
            'tokenization', 'tokenized', 'tokenizing',
            'decentralized', 'centralized',
            'autonomous', 'autonomously',
            'drone', 'drones', 'drone', 'warfare',
            'countermeasure', 'countermeasures',
            'interceptor', 'interceptors',
            'avionics', 'avionic', 'propulsion',
            'warfighter', 'warfighters', 'warfighting',
            'battlefield', 'battlespace', 'munition', 'munitions',
            'hypersonic', 'supersonic', 'subsonic',
            'ballistic', 'reusability', 'reusable',
            'tiltrotor', 'tiltrotors', 'rotorcraft',
            'helicopter', 'helicopters', 'helicopter',
            'airframe', 'airframes', 'airframer', 'airframers',
            'aerospace', 'aeronautics', 'astronautics',
            'spacecraft', 'spaceplane', 'spaceship',
            'satellite', 'satellites', 'satellite',
            'constellation', 'constellations',
            'reconnaissance', 'surveillance',
            'electromagnetic', 'spectrum',
            'antenna', 'antennas', 'antennae',
            'radar', 'lidar', 'sonar', 'sensor', 'sensors',
            'munition', 'munitions', 'warhead', 'warheads',
            'propellant', 'propellants', 'booster', 'boosters',
            'payload', 'payloads', 'fairing', 'fairings',
            'stage', 'stages', 'multistage',
            'picks', 'shovels', 'moat', 'moats',
            'compounder', 'compounders',
            'palantir', 'crowdstrike', 'sentinelone',
            'cloudflare', 'datadog', 'snowflake', 'mongodb',
            'confluent', 'elastic', 'databricks',
            'zscaler', 'palo', 'fortinet', 'darktrace',
            'broadcom', 'marvell', 'arista', 'nvidia',
            'qualcomm', 'micron', 'intel', 'amd', 'on',
            'lattice', 'ambarella', 'ceva',
            'syntiant', 'hailo', 'graphcore',
            'cerebras', 'groq', 'samba', 'nuvia',
            'tenstorrent', 'untether', 'memryx',
            'd-matrix', 'etched', 'normal',
            'chiplets', 'chiplet', 'interposer',
            'advanced', 'packaging', 'fan',
            'out', 'fan', 'out', 'wlcsp', 'flip',
            'chip', 'bga', 'lga', 'pga', 'sip', 'mcm',
            'stack', 'stacks', 'stacking', 'stacked',
            'through', 'silicon', 'via', 'tsv',
            'microbump', 'microbumps', 'hybrid', 'bonding',
            'direct', 'bond', 'interconnect', 'dbi',
            'chiplet', 'chiplets', 'die', 'dies',
            'wafer', 'wafers', 'wafer', 'scale',
            'reticle', 'reticles', 'shot', 'shots',
            'layer', 'layers', 'mask', 'masks', 'reticle',
            'stepper', 'steppers', 'scanner', 'scanners',
            'immersion', 'scanner', 'euv', 'duv', 'arf',
            'krf', 'lpp', 'lpp', 'snr', 'moore',
            'dennard', 'scaling', 'hk', 'mg', 'finfet',
            'gate', 'all', 'around', 'gaa', 'nanosheet',
            'nanowire', 'nanoribbon', 'forksheet',
            'complementary', 'fet', 'cfet', 'vfet',
            'vertical', 'fet', 'horizontal', 'fet',
            'planar', 'soi', 'fd', 'soi', 'utbb',
            'pd', 'soi', 'fully', 'depleted', 'partially',
            'depleted', 'bulk', 'cmos', 'bicmos',
            'sige', 'gan', 'gap', 'gaas', 'inp', 'sapphire',
            'silicon', 'carbide', 'sic', 'gan',
            'iii', 'v', 'ii', 'vi', 'compound',
            'epitaxy', 'epitaxial', 'mocvd', 'mbe',
            'ald', 'cvd', 'pvd', 'pecvd', 'sacvd',
            'etch', 'etches', 'etching', 'etched',
            'dry', 'etch', 'wet', 'etch', 'plasma',
            'ash', 'ashing', 'strip', 'stripping',
            'clean', 'cleaning', 'cleans', 'wet', 'bench',
            'single', 'wafer', 'clean', 'batch', 'clean',
            'planarization', 'cmp', 'chemical',
            'mechanical', 'polishing', 'dishing',
            'erosion', 'corner', 'rounding',
            'thinning', 'grinding', 'backgrinding',
            'dicing', 'saw', 'dicing', 'laser',
            'grooving', 'singulation', 'pick', 'place',
            'die', 'attach', 'wire', 'bond', 'ribbon',
            'bond', 'clip', 'bond', 'solder', 'bump',
            'pillar', 'copper', 'pillar', 'solder',
            'ball', 'reflow', 'mass', 'reflow',
            'flux', 'underfill', 'molding', 'mold',
            'compound', 'encapsulation', 'glob',
            'top', 'overmold', 'lid', 'attach',
            'thermal', 'interface', 'material', 'tim',
            'heatsink', 'spreader', 'cold', 'plate',
            'vapor', 'chamber', 'heat', 'pipe', 'fan',
            'blower', 'liquid', 'cooling', 'immersion',
            'cooling', 'single', 'phase', 'two', 'phase',
            'dielectric', 'fluid', 'thermal',
            'management', 'junction', 'temperature',
            'tdp', 'thermal', 'design', 'power',
            'power', 'dissipation', 'wattage',
            'performance', 'per', 'watt', 'ppw',
            'efficiency', 'efficient', 'inefficient',
            'power', 'gating', 'clock', 'gating',
            'dynamic', 'voltage', 'frequency', 'scaling',
            'dvfs', 'adaptive', 'voltage', 'scaling',
            'avs', 'body', 'biasing', 'forward',
            'biasing', 'reverse', 'biasing',
            'leakage', 'power', 'active', 'power',
            'static', 'power', 'dynamic', 'power',
            'switching', 'power', 'short', 'circuit',
            'power', 'subthreshold', 'leakage',
            'gate', 'leakage', 'junction', 'leakage',
            'btbt', 'gate', 'induced', 'drain',
            'leakage', 'gidl', 'drain', 'induced',
            'barrier', 'lowering', 'dibl',
            'short', 'channel', 'effect', 'sces',
            'velocity', 'saturation', 'velocity',
            'overshoot', 'ballistic', 'transport',
            'quasi', 'ballistic', 'diffusive',
            'transport', 'mobility', 'carrier',
            'mobility', 'electron', 'mobility', 'hole',
            'mobility', 'effective', 'mass', 'density',
            'of', 'states', 'dos', 'bandgap', 'band',
            'gap', 'conduction', 'band', 'valence',
            'band', 'fermi', 'level', 'work', 'function',
            'schottky', 'barrier', 'ohmic', 'contact',
            'specific', 'contact', 'resistivity',
            'contact', 'resistance', 'sheet', 'resistance',
            'via', 'resistance', 'line', 'resistance',
            'rc', 'delay', 'rc', 'time', 'constant',
            'wire', 'delay', 'interconnect', 'delay',
            'global', 'interconnect', 'local',
            'interconnect', 'intermediate', 'interconnect',
            'beol', 'feol', 'meol', 'middle', 'of', 'line',
            'front', 'end', 'of', 'line', 'back', 'end',
            'of', 'line', 'contact', 'layer', 'metal',
            'layer', 'via', 'layer', 'interlayer',
            'dielectric', 'ild', 'intermetal',
            'dielectric', 'imd', 'low', 'k', 'dielectric',
            'ultra', 'low', 'k', 'elk', 'high', 'k',
            'dielectric', 'hk', 'mg', 'gate', 'stack',
            'metal', 'gate', 'replacement', 'metal',
            'gate', 'rmg', 'gate', 'last', 'gate', 'first',
            'dummy', 'gate', 'sacrificial', 'gate',
            'spacer', 'spacers', 'sidewall', 'spacer',
            'offset', 'spacer', 'nitride', 'spacer',
            'oxide', 'spacer', 'sige', 'channel',
            'strain', 'strained', 'channel',
            'stress', 'liner', 'stress', 'memorization',
            'smt', 'stress', 'proximity', 'technique',
            'spo', 'embedded', 'sige', 'esige',
            'source', 'drain', 'sd', 'raised',
            'source', 'drain', 'rsd', 'recessed',
            'source', 'drain', 'lightly', 'doped',
            'drain', 'ldd', 'halo', 'pocket', 'implant',
            'extension', 'implant', 'source', 'drain',
            'implant', 'deep', 'source', 'drain',
            'implant', 'silicidation', 'silicide',
            'nisi', 'tisi', 'cosi', 'ptsi',
            'self', 'aligned', 'silicide', 'salicide',
            'contact', 'silicide', 'titanium',
            'silicide', 'cobalt', 'silicide', 'nickel',
            'silicide', 'platinum', 'silicide',
            'dopant', 'activation', 'anneal',
            'spike', 'anneal', 'laser', 'anneal',
            'flash', 'anneal', 'rapid', 'thermal',
            'processing', 'rtp', 'rapid', 'thermal',
            'anneal', 'rta', 'rapid', 'thermal',
            'oxidation', 'rto', 'furnace', 'anneal',
            'batch', 'furnace', 'vertical', 'furnace',
            'horizontal', 'furnace', 'oxidation',
            'nitridation', 'nitride', 'deposition',
            'oxide', 'deposition', 'polysilicon',
            'deposition', 'amorphous', 'silicon',
            'deposition', 'epitaxial', 'deposition',
            'selective', 'epitaxy', 'selective',
            'epitaxial', 'growth', 'seg',
            'semiconductor', 'fabrication', 'fab',
            'fabs', 'foundry', 'foundries', 'fablite',
            'fabless', 'idm', 'idms', 'pure', 'play',
            'foundry', 'integrated', 'device',
            'manufacturer', 'design', 'house',
            'design', 'services', 'design', 'win',
            'design', 'wins', 'tapeout', 'tape',
            'out', 'spin', 'in', 'mask', 'tapeout',
            'reticle', 'enhancement', 'technology',
            'ret', 'optical', 'proximity', 'correction',
            'opc', 'source', 'mask', 'optimization',
            'smo', 'inverse', 'lithography',
            'technology', 'ilt', 'curvilinear',
            'mask', 'stochastic', 'effects',
            'roughness', 'line', 'edge', 'roughness',
            'ler', 'line', 'width', 'roughness', 'lwr',
            'critical', 'dimension', 'cd', 'cd',
            'uniformity', 'cdu', 'cd', 'control',
            'overlay', 'overlay', 'control',
            'alignment', 'wafer', 'alignment',
            'field', 'by', 'field', 'alignment',
            'global', 'alignment', 'advanced', 'process',
            'control', 'apc', 'run', 'to', 'run',
            'control', 'r2r', 'fault', 'detection',
            'fd', 'root', 'cause', 'analysis',
            'yield', 'enhancement', 'yield',
            'ramp', 'yield', 'learning', 'yield',
            'modeling', 'defect', 'density',
            'killer', 'defects', 'random', 'defects',
            'systematic', 'defects', 'parametric',
            'defects', 'functional', 'defects',
            'bin', 'sort', 'binning', 'test', 'program',
            'probe', 'card', 'probe', 'needle',
            'cantilever', 'probe', 'membrane', 'probe',
            'vertical', 'probe', 'drill', 'probe',
            'final', 'test', 'burn', 'in', 'bi',
            'burn', 'in', 'board', 'bibo', 'burn',
            'in', 'oven', 'life', 'test', 'htol',
            'operating', 'life', 'test', 'olt',
            'electrostatic', 'discharge', 'esd',
            'latchup', 'latch', 'up',
            'electromigration', 'em', 'stress',
            'induced', 'voiding', 'siv',
            'stress', 'migration', 'sm', 'thermal',
            'cycling', 'temperature', 'cycling',
            'humidity', 'test', 'hast', 'biased',
            'hast', 'bhast', 'pressure', 'cooker',
            'autoclave', 'high', 'temperature',
            'storage', 'life', 'htsl', 'solder',
            'reflow', 'sensitivity', 'msl',
            'moisture', 'sensitivity', 'level',
            'preconditioning', 'precon',
            'acoustic', 'microscopy', 'sam',
            'x', 'ray', 'inspection', 'automated',
            'x', 'ray', 'inspection', 'axi',
            'scanning', 'electron', 'microscopy',
            'sem', 'transmission', 'electron',
            'microscopy', 'tem', 'focused', 'ion',
            'beam', 'fib', 'dual', 'beam', 'fib',
            'sem', 'energy', 'dispersive', 'x',
            'ray', 'spectroscopy', 'eds', 'edx',
            'wavelength', 'dispersive', 'x', 'ray',
            'spectroscopy', 'wds', 'wdx',
            'x', 'ray', 'photoelectron', 'spectroscopy',
            'xps', 'auger', 'electron', 'spectroscopy',
            'aes', 'secondary', 'ion', 'mass',
            'spectrometry', 'sims', 'atomic', 'force',
            'microscopy', 'afm', 'scanning', 'probe',
            'microscopy', 'spm', 'scanning',
            'tunneling', 'microscopy', 'stm',
            'profilometry', 'profilometer',
            'ellipsometry', 'spectroscopic',
            'ellipsometry', 'se', 'reflectometry',
            'interferometry', 'scatterometry',
            'thickness', 'measurement', 'film',
            'thickness', 'refractive', 'index',
            'optical', 'constants', 'extinction',
            'coefficient', 'absorption', 'coefficient',
            'reflectance', 'transmittance', 'absorbance',
            'raman', 'spectroscopy', 'photoluminescence',
            'pl', 'cathodoluminescence', 'cl',
            'electroluminescence', 'el',
            'four', 'point', 'probe', 'spreading',
            'resistance', 'analysis', 'sra',
            'carrier', 'lifetime', 'minority',
            'carrier', 'lifetime', 'recombination',
            'lifetime', 'leakage', 'current',
            'breakdown', 'voltage', 'threshold',
            'voltage', 'vt', 'saturation', 'current',
            'idsat', 'drive', 'current', 'ion',
            'off', 'current', 'ioff', 'transistor',
            'transconductance', 'gm',
            'output', 'conductance', 'go',
            'intrinsic', 'gain', 'av', 'unity',
            'gain', 'frequency', 'ft', 'maximum',
            'oscillation', 'frequency', 'fmax',
            'noise', 'figure', 'nf', 'flicker',
            'noise', 'white', 'noise', 'shot', 'noise',
            'thermal', 'noise', 'signal', 'to', 'noise',
            'ratio', 'snr', 'distortion', 'thd',
            'spurious', 'free', 'dynamic', 'range',
            'sfdr', 'intermodulation', 'im',
            'harmonic', 'distortion', 'hd',
            'power', 'added', 'efficiency', 'pae',
            'drain', 'efficiency', 'power', 'gain',
            'power', 'output', 'compression', 'point',
            'p1db', 'third', 'order', 'intercept',
            'point', 'oip3', 'iip3',
            'spurious', 'emissions', 'spectral',
            'purity', 'phase', 'noise', 'jitter',
            'root', 'mean', 'square', 'rms', 'peak',
            'to', 'peak', 'peak', 'peak', 'pk',
            'pk', 'pk', 'amplitude', 'amplitude',
            'modulation', 'am', 'frequency',
            'modulation', 'fm', 'phase', 'modulation',
            'pm', 'pulse', 'modulation', 'pwm',
            'amplitude', 'shift', 'keying', 'ask',
            'frequency', 'shift', 'keying', 'fsk',
            'phase', 'shift', 'keying', 'psk',
            'quadrature', 'amplitude', 'modulation',
            'qam', 'orthogonal', 'frequency', 'division',
            'multiplexing', 'ofdm', 'spread',
            'spectrum', 'direct', 'sequence',
            'dsss', 'frequency', 'hopping', 'fhss',
            'ultra', 'wideband', 'uwb', 'lpwa',
            'nb', 'iot', 'lte', 'cat', 'm',
            'cat', 'nb', 'cat', 'lte',
            'mimo', 'massive', 'mimo', 'beamforming',
            'precoding', 'spatial', 'multiplexing',
            'diversity', 'transmit', 'diversity',
            'receive', 'diversity', 'polarization',
            'diversity', 'antenna', 'configurations',
            'adaptive', 'modulation', 'coding',
            'amc', 'hybrid', 'arq', 'harq',
            'automatic', 'repeat', 'request', 'arq',
            'forward', 'error', 'correction', 'fec',
            'convolutional', 'code', 'turbo', 'code',
            'ldpc', 'polar', 'code', 'rs', 'code',
            'bch', 'code', 'hamming', 'code',
            'trellis', 'code', 'modulation', 'tcm',
            'interleaving', 'scrambling', 'scrambler',
            'descrambler', 'synchronization', 'sync',
            'channel', 'estimation', 'channel',
            'equalization', 'channel', 'sounding',
            'pilots', 'reference', 'signals',
            'demodulation', 'reference', 'signal',
            'dmrs', 'sounding', 'reference', 'signal',
            'srs', 'phase', 'tracking', 'reference',
            'signal', 'ptrs', 'channel', 'state',
            'information', 'csi', 'rank', 'indicator',
            'ri', 'precoding', 'matrix', 'indicator',
            'pmi', 'channel', 'quality', 'indicator',
            'cqi', 'modulation', 'coding', 'scheme',
            'mcs', 'transport', 'block', 'size', 'tbs',
            'resource', 'block', 'rb', 'resource',
            'element', 're', 'physical', 'resource',
            'block', 'prb', 'virtual', 'resource',
            'block', 'vrb', 'resource', 'allocation',
            'scheduling', 'scheduler', 'proportional',
            'fair', 'scheduler', 'round', 'robin',
            'scheduler', 'weighted', 'fair', 'queuing',
            'wfq', 'carrier', 'aggregation', 'ca',
            'dual', 'connectivity', 'dc', 'nr',
            'lte', 'nr', 'dual', 'connectivity',
            'en', 'dc', 'ne', 'dc', 'ng', 'dc',
            'standalone', 'sa', 'non', 'standalone',
            'nsa', 'core', 'network',
            'epc', 'evolved', 'packet', 'core',
            '5gc', '5g', 'core', 'ng', 'core',
            'access', 'network', 'ran', 'radio',
            'access', 'network', 'ng', 'ran',
            'next', 'generation', 'radio', 'access',
            'network', 'gnb', 'gnodeb', 'enb',
            'enodeb', 'cu', 'central', 'unit',
            'du', 'distributed', 'unit', 'ru',
            'radio', 'unit', 'fronthaul', 'midhaul',
            'backhaul', 'open', 'ran', 'oran',
            'virtualized', 'ran', 'vran',
            'cloud', 'ran', 'cran', 'radio',
            'access', 'network', 'intelligent',
            'controller', 'ric', 'non', 'real',
            'time', 'ric', 'near', 'real', 'time',
            'ric', 'e2', 'interface', 'a1',
            'interface', 'o1', 'interface',
            'xapp', 'rapp', 'service',
            'management', 'orchestration', 'smo',
            'software', 'defined', 'networking', 'sdn',
            'network', 'function', 'virtualization', 'nfv',
            'virtual', 'network', 'function', 'vnf',
            'containerized', 'network', 'function', 'cnf',
            'network', 'slicing', 'slice', 'slices',
            'embb', 'urllc', 'mmtc', 'mimo',
            'scheduling', 'bearer', 'eps', 'bearer',
            'drb', 'srb', 'qos', 'flow', 'gbr',
            'non', 'gbr', 'qci', '5qi', 'reflective',
            'qos', 'flow', 'labeling', 'rqi',
            'traffic', 'steering', 'traffic',
            'splitting', 'traffic', 'switching',
            'dual', 'connectivity', 'split', 'bearer',
            'secondary', 'cell', 'group', 'scg',
            'primary', 'secondary', 'cell', 'pscell',
            'special', 'cell', 'spcell',
            'master', 'cell', 'group', 'mcg',
            'primary', 'cell', 'pcell', 'secondary',
            'cell', 'scell', 'carrier', 'aggregation',
            'bandwidth', 'part', 'bwp', 'initial',
            'bwp', 'active', 'bwp', 'default', 'bwp',
            'supplementary', 'uplink', 'sul',
            'licensed', 'access', 'laa', 'nr',
            'unlicensed', 'nr', 'u', 'lte', 'u',
            'listen', 'before', 'talk', 'lbt',
            'cat', 'lbt', 'cat', 'lbt',
        }
        
        real_misspellings = [w for w in misspelled if w not in signal_jargon]
        
        if real_misspellings:
            print(f"\n{s}: POTENTIAL MISSPELLINGS: {real_misspellings}")
        else:
            print(f"{s}: OK ({len(misspelled)} jargon words filtered)")
    else:
        print(f"{s}: OK (no misspellings)")
