// Post-build script
// Restores known-good design assets from _backup_base over the build.js output,
// preserving article/ticker/sector pages generated by build.js.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const BACKUP = path.join(ROOT, '_backup_base');

// ─── 1. Restore homepage, CSS, JS, images, favicon from backup ───
const RESTORE = [
  'index.html',
  'favicon.ico',
];

// Copy individual files
for (const f of RESTORE) {
  const src = path.join(BACKUP, f);
  const dest = path.join(DIST, f);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, dest);
    console.log('✓ ' + f + ' (' + fs.statSync(dest).size + ' bytes)');
  }
}

// Copy entire directories from backup
const RESTORE_DIRS = ['css', 'js', 'img'];
for (const dir of RESTORE_DIRS) {
  const srcDir = path.join(BACKUP, dir);
  const destDir = path.join(DIST, dir);
  if (fs.existsSync(srcDir)) {
    fs.rmSync(destDir, { recursive: true, force: true });
    fs.cpSync(srcDir, destDir, { recursive: true });
    console.log('✓ ' + dir + '/ restored');
  }
}

// ─── 2. Inject new glassmorphism comments.js ───
const commentsSrc = path.join(ROOT, 'public', 'js', 'comments.js');
const commentsDest = path.join(DIST, 'js', 'comments.js');
if (fs.existsSync(commentsSrc)) {
  fs.copyFileSync(commentsSrc, commentsDest);
  console.log('✓ comments.js injected (' + fs.statSync(commentsDest).size + ' bytes)');
}

// ─── 3. Restore static pages from backups ───
const pages = [
  ['account-settings.html', 'dist/account/settings/index.html'],
  ['signal-vs-the-street.html', 'dist/signal-vs-the-street/index.html'],
  ['av-style-sample.html', 'dist/av-style-sample.html'],
];
for (const [backupName, dest] of pages) {
  const backupFile = path.join(ROOT, backupName);
  const destFull = path.join(ROOT, dest);
  if (fs.existsSync(backupFile)) {
    fs.mkdirSync(path.dirname(destFull), { recursive: true });
    fs.copyFileSync(backupFile, destFull);
    console.log('✓ ' + dest + ' (restored)');
  }
}

// ─── 4. Copy API serverless functions ───
const apiDir = path.join(ROOT, 'api');
const distApiDir = path.join(DIST, 'api');
if (fs.existsSync(apiDir)) {
  fs.mkdirSync(distApiDir, { recursive: true });
  const apiFiles = fs.readdirSync(apiDir);
  for (const f of apiFiles) {
    fs.copyFileSync(path.join(apiDir, f), path.join(distApiDir, f));
    console.log('✓ api/' + f);
  }
}

// ─── Summary ───
const htmlSize = fs.statSync(path.join(DIST, 'index.html')).size;
const cssSize = fs.statSync(path.join(DIST, 'css', 'main.css')).size;
const articleCount = fs.existsSync(path.join(DIST, 'article')) 
  ? fs.readdirSync(path.join(DIST, 'article')).length 
  : 0;
console.log('✅ Post-build complete — ' + htmlSize + 'b homepage, ' + cssSize + 'b CSS, ' + articleCount + ' articles');
