// Post-build script
// Restores known-good design assets from _backup_base over the build.js output,
// preserving article/ticker/sector pages generated by build.js.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const BACKUP = path.join(ROOT, '_backup_base');

// ─── 1. Restore CSS, JS, images, favicon from backup ───
// NOTE: index.html is NOT restored from backup — build.js generates the authoritative homepage.
// Restoring from backup was dropping newly published articles from the live site.
const RESTORE = [
  'favicon.ico',
];

// Copy individual files
for (const f of RESTORE) {
  const src = path.join(BACKUP, f);
  const dest = path.join(DIST, f);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, dest);
    console.log('✓ ' + f + ' (' + fs.statSync(dest).size + ' bytes)');
  }
}

// Copy css/ and js/ from backup (replace entirely)
const REPLACE_DIRS = ['css', 'js'];
for (const dir of REPLACE_DIRS) {
  const srcDir = path.join(BACKUP, dir);
  const destDir = path.join(DIST, dir);
  if (fs.existsSync(srcDir)) {
    fs.rmSync(destDir, { recursive: true, force: true });
    fs.cpSync(srcDir, destDir, { recursive: true });
    console.log('✓ ' + dir + '/ restored');
  }
}

// MERGE img/ — keep build's img/articles/, add backup's root images
const backupImgDir = path.join(BACKUP, 'img');
const distImgDir = path.join(DIST, 'img');
if (fs.existsSync(backupImgDir)) {
  const backupFiles = fs.readdirSync(backupImgDir);
  let copied = 0;
  for (const f of backupFiles) {
    const src = path.join(backupImgDir, f);
    const dest = path.join(distImgDir, f);
    const stat = fs.statSync(src);
    if (stat.isFile()) {
      fs.copyFileSync(src, dest);
      copied++;
    } else if (stat.isDirectory() && !fs.existsSync(dest)) {
      fs.cpSync(src, dest, { recursive: true });
    }
  }
  console.log('✓ img/ merged (' + copied + ' backup files, kept build articles)');
}

// ─── 2. Inject new glassmorphism comments.js ───
const commentsSrc = path.join(ROOT, 'public', 'js', 'comments.js');
const commentsDest = path.join(DIST, 'js', 'comments.js');
if (fs.existsSync(commentsSrc)) {
  fs.copyFileSync(commentsSrc, commentsDest);
  console.log('✓ comments.js injected (' + fs.statSync(commentsDest).size + ' bytes)');
}

// ─── 3. Restore static pages from backups ───
const pages = [
  ['account-settings.html', 'dist/account/settings/index.html'],
  ['signal-vs-the-street.html', 'dist/signal-vs-the-street/index.html'],
  ['av-style-sample.html', 'dist/av-style-sample.html'],
];
for (const [backupName, dest] of pages) {
  const backupFile = path.join(ROOT, backupName);
  const destFull = path.join(ROOT, dest);
  if (fs.existsSync(backupFile)) {
    fs.mkdirSync(path.dirname(destFull), { recursive: true });
    fs.copyFileSync(backupFile, destFull);
    console.log('✓ ' + dest + ' (restored)');
  }
}

// ─── 4. Copy API serverless functions ───
const apiDir = path.join(ROOT, 'api');
const distApiDir = path.join(DIST, 'api');
if (fs.existsSync(apiDir)) {
  fs.mkdirSync(distApiDir, { recursive: true });
  const apiFiles = fs.readdirSync(apiDir);
  for (const f of apiFiles) {
    fs.copyFileSync(path.join(apiDir, f), path.join(distApiDir, f));
    console.log('✓ api/' + f);
  }
}

// ─── 5. Fill missing article images with default fallback ───
const defaultImg = path.join(BACKUP, 'img', '_default.jpg');
const articlesDir = path.join(DIST, 'img', 'articles');
if (fs.existsSync(defaultImg) && fs.existsSync(articlesDir)) {
  // Scan homepage for /img/articles/ and /images/articles/ references
  const htmlContent = fs.readFileSync(path.join(DIST, 'index.html'), 'utf8');
  const imgRefs = htmlContent.match(/\/i(mg|mages)\/articles\/[^"]+\.jpg/g) || [];
  const uniqueRefs = [...new Set(imgRefs)];
  let filled = 0;
  for (const ref of uniqueRefs) {
    // Normalize /images/ → /img/
    const normalized = ref.replace('/images/', '/img/');
    const destFile = path.join(DIST, normalized);
    if (!fs.existsSync(destFile)) {
      fs.mkdirSync(path.dirname(destFile), { recursive: true });
      fs.copyFileSync(defaultImg, destFile);
      filled++;
    }
  }
  if (filled > 0) console.log('✓ ' + filled + ' missing article images → default fallback');
}

// ─── Summary ───
const htmlSize = fs.statSync(path.join(DIST, 'index.html')).size;
const cssSize = fs.statSync(path.join(DIST, 'css', 'main.css')).size;
const articleCount = fs.existsSync(path.join(DIST, 'article')) 
  ? fs.readdirSync(path.join(DIST, 'article')).length 
  : 0;
console.log('✅ Post-build complete — ' + htmlSize + 'b homepage, ' + cssSize + 'b CSS, ' + articleCount + ' articles');
